version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: services-hub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: services-hub
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - services-hub-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: services-hub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - services-hub-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: services-hub-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/services-hub?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-at-least-32-characters-long
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-at-least-32-characters-long
      CORS_ORIGIN: http://localhost:3000,http://localhost:4173,http://localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - services-hub-network

  # Frontend (if running in Docker)
  frontend:
    build:
      context: ../services-hub
      dockerfile: Dockerfile
    container_name: services-hub-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - services-hub-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  services-hub-network:
    driver: bridge
